### PR TITLE
adding resource endpoints for tailing each log file, and getting conf…

### PR DESCRIPTION
**Pull request by drewkerrigan**
Added following new endpoints:

```
/explore/clusters/default/nodes/riak@127.0.0.1/console_log?rows=1000
/explore/clusters/default/nodes/riak@127.0.0.1/crash_log?rows=1000
/explore/clusters/default/nodes/riak@127.0.0.1/erlang_log?rows=1000
/explore/clusters/default/nodes/riak@127.0.0.1/error_log?rows=1000
/explore/clusters/default/nodes/riak@127.0.0.1/runerl_log?rows=1000
/explore/clusters/default/nodes/riak@127.0.0.1/riak_conf
/explore/clusters/default/nodes/riak@127.0.0.1/advanced_conf
```

Note that `-H 'Accept: plain/text'` should be added to requests in order to get the plain text version. The `?rows=1000` parameter gives 1000 (default) lines from the end of the file.

Also fixed the `/explore/clusters/default/nodes/riak@127.0.0.1` endpoint. Also added Riak Version to the `/explore/clusters` output.

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Tested out this PR; most stuff works, couple of errors though.

1. Get node detail endpoint (`curl localhost:9000/explore/clusters/localdev/nodes/dev1@127.0.0.1`) works now, thanks!

2. List all nodes for a cluster (`curl localhost:9000/explore/clusters/localdev/nodes/`) works great.

3. List all clusters breaks, however, with a `500 Internal Server Error`:

    ```erlang
{error,{exit,{json_encode,{bad_term,{badrpc,nodedown}}},
             [{mochijson2,json_encode,2,
                          [{file,"src/mochijson2.erl"},{line,163}]},
              {mochijson2,'-json_encode_proplist/2-fun-0-',3,
                          [{file,"src/mochijson2.erl"},{line,181}]},
              {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},
              {mochijson2,json_encode_proplist,2,
                          [{file,"src/mochijson2.erl"},{line,184}]},
              {mochijson2,'-json_encode_array/2-fun-0-',3,
                          [{file,"src/mochijson2.erl"},{line,171}]},
              {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},
              {mochijson2,json_encode_array,2,
                          [{file,"src/mochijson2.erl"},{line,173}]},
              {mochijson2,'-json_encode_proplist/2-fun-0-',3,
                          [{file,"src/mochijson2.erl"},{line,181}]}]}}
    ```

4. The Riak versions all work (in cluster detail, nodes list, and node detail). (Although I discovered that in our 'build a devrel cluster from source', we don't set the `APP_VERSION` environment variable correctly -- boooo. So, the version will be missing for those users. Not much we can do there (short of submitting a PR to the main riak repo.))

5. The `$node/riak_conf` and `$node/advanced_conf` endpoints work as advertised.

6. Do you think it's worth implementing a `$node/configs` endpoint, that will list the available/applicable config files that one can request through the API? (For example, how difficult would it be to support the old-style `vm.args` and `app.config` for users who upgraded to 2.0 and kept the configs?). Or should the client/front end just check each config endpoint, and generate a list that way?

7. The 5 log endpoints work as expected. (Although, I don't have an `erlang_log` on one of the nodes. When I requested it through the endpoint, I expected a 404, but it gave me a 200 with empty content.)

8. Same as for configs (but more relevant in case of logs), can we implement a `$node/logs` endpoint to list the available logs? (So that we can also include the `solr.log`, and the various log-rotated versions of the 5 supported logs above (like `error.log.4` etc)?

9. Incidentally, this functionality is *badass*, and I can't wait to have it available for users!

**Comment by dmitrizagidulin** [comment]
Oh, now that I think about it, the 'list clusters' 500 error is probably due to the fact that a couple of my clusters defined in the explorer config are pointing to nodes that aren't running at the moment.

So that's likely a separate issue, but still, we should probably catch that error (and still list those clusters, but with `version: unavailable` and `type: unavailable`).

**Comment by dmitrizagidulin** [comment]
More notes on the 500 Server Error above. I'm leaving them as comments on this PR, since it only affects this branch (I assume the 'list clusters' now breaks because we're reaching out to the nodes to execute version- and type-getting code).

The 500 error happens in 3 cases that I've encountered so far:

1. When the explorer config contains a cluster definition that's pointing to a cluster which is completely down/unavailable.
2. If the config file points to a valid/running cluster, but it's not on the default riak id (riak@127..), it also errors out. (It expects there to be a default cluster at the default location.
3. If the config points to a valid cluster, but if any of the nodes in that cluster are down, it also errors.

Obviously, we want to trap those errors, and use `unavailable` or `unknown` (take your pick) for riak version and riak type, for those nodes. But this also brings up a couple of issues:

* In the next few tickets, we're going to be polling all the nodes periodically via Riak ping, from the client. (And also going to be polling the `/nodes` explorer endpoint, to get the current list). It may make a lot of sense for us to include an `available` field, in the list of nodes for a cluster, so that clients can just poll a single Explorer api endpoint, instead of each node. Since we're contacting each node anyway, to get the version etc, we already know whether it's reachable or not. Might as well put that info in the response?

* Though speaking of which, how expensive is the version/type operation? Will it get unwieldy, once multiple Explorer clients are polling a large cluster, every few seconds? If we find that it adds up, we can do a couple of things: a) cache the version/type info on the API-side somehow, or b) only return the version/type fields on the cluster detail request (by only getting the contact node's info). And not on the /nodes request.

**Comment by drewkerrigan** [comment]
@dmitrizagidulin Update:

* Refactored routes to be easier to read and maintain
* Deduplicated a lot of code by creating a `re_wm_util.erl`
* Removed `riak_version` and `riak_type` from `/explore/clusters/default/nodes/riak@127.0.0.1` and `/explore/clusters/default/nodes` because of concerns around number of requests Dmitri brought up (they still exist in the /clusters endpoint).
* Added `available` field to `/clusters` and `/clusters/$cluster` endpoint representing availability of the contact node as suggested
* Fixed various `{badrpc, nodedown}` errors in places such as `/explore/clusters` when some clusters have default nodes that can't be reached.
* Replaced `riak_version` and `riak_type` with `unavailable` when this happens as suggested
* Removed `$node/riak_conf` and `$node/advanced_conf` endpoints in favor of...
* Added `$node/config/files`, `$node/config/files/$file` (`$node/config` still gives effective). Still must supply `-H 'Accept: plain/text'` to get textual version.
* Removed the 5 log file end points in favor of...
* Added `$node/log/files`, `$node/log/files/$file`. Still must supply `-H 'Accept: plain/text'` to get textual version.
* Log files which don't exist should now return 404
* The list of log files should also now include all of the `.1`, `.2`, etc rolled logs

**Pull request merged**
